export enum StatusCode {
  OK = "OK",
  PLAYER_INVALID = "PLAYER_INVALID",
  ID_SECRET_INVALID = "ID_SECRET_INVALID",
  GAME_CONFIG_INVALID = "GAME_CONFIG_INVALID",
  GAME_CREATOR_INVALID = "GAME_CREATOR_INVALID",
  GAME_NOT_EXISTS = "GAME_NOT_EXISTS",
  PLAYER_ROOM_INVALID = "PLAYER_ROOM_INVALID",
  GAME_FULL = "GAME_FULL",
}
